---
- hosts: localhost
  become: yes
  vars:
     version: "9.0.4"
     source_url: "https://download.java.net/java/GA/jdk9/9.0.4/binaries/openjdk-{{ version }}_linux-x64_bin.tar.gz"
     install_path: "/opt/jdk/"
     mode: "644"
     user: "ec2-user"
     unarchive_src: "/opt/jdk/openjdk-{{ version }}_linux-x64_bin.tar.gz"
     latest_jdk: "/opt/jdk/jdk-{{ version }}/bin/java"
  tasks:
     - name: Downloading Java {{ version }} tar file
       get_url:
         url: "{{ source_url }}"
         dest: "{{ install_path}}"
         mode: "{{ mode }}"
       become: yes

     - name: untar the Java {{ version }}
       unarchive:
          src: "{{ unarchive_src}}"
          dest: "{{ install_path}}"
          remote_src: yes

     - name: creating link
       shell: "alternatives --install /usr/bin/java java {{ latest_jdk }} 200000"
       become: true

     - name: alternatives set
       alternatives:
          name: java
          path: "{{ latest_jdk }}"
       become: true

     - name: set JAVA_home in bash profile
       lineinfile:
               path: /home/"{{ user }}"/.bash_profile
               regexp: '^export JAVA_HOME='
               line: export JAVA_HOME={{ latest_jdk }}
               owner: "{{ user }}"
               group: "{{ user }}"
       become_user: "{{ user }}"
